repositories {
    mavenLocal()
    maven {
        name "Dynmap"
        url "https://repo.mikeprimm.com/"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation fg.deobf("curse.maven:minecolonies-245506:6790449")
    implementation fg.deobf("curse.maven:structurize-298744:6710737")
    implementation fg.deobf("curse.maven:domum-ornamentum-527361:6721676")
    implementation fg.deobf("curse.maven:blockui-522992:6646544")


    compileOnly fg.deobf("us.dynmap:DynmapCoreAPI:${project.dynmapApiVersion}")
    implementation fg.deobf("curse.maven:dynmapforge-59433:5442840")

    library("org.jsoup:jsoup:${project.jsoupVersion}")
    contained("org.jsoup:jsoup:${project.jsoupVersion}")
}